### ISSUE TITLE
Throttle Fan

### ISSUE THREAD

**Issue by Bobbrockhouse** [n1ksn/dcc-ex-bluepill-throttle-7#1]
Electronics and trains enthusiast.

**Comment by Bobbrockhouse** [comment]
Included INO file will not compile in Arduino IDE. Error messages point to
use of the DCCEXProtocol library. "myDelegate not declared in this scope"
and "MyDelegate does not name a type". Not a coder expert so need some 
help.

**Comment by n1ksn** [comment]
Bob, I'm sorry you ran into a problem compiling my "sketch."  I just 
tried a compile using the latest DCC EX Protocol Library, version 
0.0.13, in the Arduino IDE I have installed (2.2.1) and it went through 
OK.  All I can think of is that it has to do with the version of the 
DCC-EX library or the version of the Arduino IDE. Of course, you need to 
install the DCC-EX library in your Arduino IDE.  Andy

**Comment by Bobbrockhouse** [comment]
Appreciate your reply, really want to build this throttle.
Have used the versions you quote but may reload incase something did not stick. Only other point to raisewould be regards the actual ".h" file, does this need to be edited from what is provided in the library install ?
Many thanks, Bob

    On Sunday, May 19, 2024 at 11:18:07 PM GMT+9:30, n1ksn ***@***.***> wrote:  
 
 

Bob, I'm sorry you ran into a problem compiling my "sketch."  I just 
tried a compile using the latest DCC EX Protocol Library, version 
0.0.13, in the Arduino IDE I have installed (2.2.1) and it went through 
OK.  All I can think of is that it has to do with the version of the 
DCC-EX library or the version of the Arduino IDE. Of course, you need to 
install the DCC-EX library in your Arduino IDE.  Andy

**Comment by Bobbrockhouse** [comment]
Another avenue Andy, I have installed the STM32duino core in the IDE.Are you using the other version, official from STM ?
Maybe be relevant to be using the same core you are using ?
Cheers

    On Sunday, May 19, 2024 at 11:18:07 PM GMT+9:30, n1ksn ***@***.***> wrote:  
 
 

Bob, I'm sorry you ran into a problem compiling my "sketch."  I just 
tried a compile using the latest DCC EX Protocol Library, version 
0.0.13, in the Arduino IDE I have installed (2.2.1) and it went through 
OK.  All I can think of is that it has to do with the version of the 
DCC-EX library or the version of the Arduino IDE. Of course, you need to 
install the DCC-EX library in your Arduino IDE.  Andy

**Comment by n1ksn** [comment]
Bob, I'm not sure what *.h file you are referring to.  I just installed 
the DCC-EX library via the Arduino IDE and made the library function 
calls as documented on the DCC-EX website in the *.ino source file.  I 
made no mods to the library.  Andy

**Comment by n1ksn** [comment]
I installed the additional board manager at 
https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json 
and all the other stuff was auto installed after that.

**Comment by Bobbrockhouse** [comment]
Many thanks for the feedback, have done a "clean" IDE and librariesre-install. With my curiosity satisfied, will give it another try.
Do appreciate your indulgence, not wishing to engage you in emailping pong.
Cheers

    On Monday, May 20, 2024 at 12:54:52 PM GMT+9:30, n1ksn ***@***.***> wrote:  
 
 

I installed the additional board manager at 
https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json 
and all the other stuff was auto installed after that.

**Comment by Bobbrockhouse** [comment]
Success, clean install of IDE and libraries did the trick. Compiles slowly but
correctly. Again, thanks for the feedback. Issue resolved, can be deleted.

**Comment by n1ksn** [comment]
Bob, I am very happy that you got it to compile!  Too bad it was so much 
work for you.  I hope the hardware side proceeds without any major 
issues.  I added the rotary encoder as an add-on peripheral at the 
request of someone in the Facebook DCC-EX forum, as I rarely use it 
myself (my layout is very small).  With the encoder I had in my junkbox 
there are two detents per speed step.  I am very happy someone is 
actually trying to build the throttle.  Andy

**Comment by Bobbrockhouse** [comment]
Andy,
I figured a clean install, using your IDE and library versions was the only way to proceed. It has long been my view that version numbers are important as it can make the difference between a compile or fail.

The time to do a clean install was well worth it to me. So I consider the
"issue" is now resolved, and can be closed. Who does the closing ?
 Just for info, I use the "Trainboard - DCC" forum where you can view the
thread "blue pill throttle" that has developed quite a number of viewers.

I would welcome any updates to your project as you see fit.
Cheers

**Comment by Bobbrockhouse** [comment]
Just when I thought.....another question if I may.
What option in the IDE did you use to load the INO file ?
I noted the ST-LINK doesn't show in the options of load
method. If I need to get something else, I will.
Thanks again

**Comment by n1ksn** [comment]
Hi Bob.

I went to the Arduino IDE installation I used to program the Blue Pill 
and the Upload Method menu item is set at STM32CubeProgrammer (SWD).  I 
used the ST-LINK connected to the four end pins on the Blue Pill board.  
Here's a webpage that uses the same method: 
https://electropeak.com/learn/how-to-program-stm32-blue-pill-stm32f103c8t6-with-arduino-ide/ 


Other people have used serial  programming, but I like using the ST-LINK 
because it hooks up to those end pins instead of port pins.  Also, I 
can't remember if I had to separately download the programming software 
or if it was done when all the other STM32 library stuff was installed.  
And be sure to set the Port menu item to the USB port the ST-LINK is put 
in (which I've forgotten more than once).

Good luck!

Andy

**Comment by Bobbrockhouse** [comment]
Great news and relief. I want to use my ST-Link when it arrives.
Your comment reflects my thoughts of using the (SWD) option
and confirms I am using the same STM package as you. My
interest told me to install the Cube programmer software and play around.
I found it functions with binary files. Then I find the Arduino IDE will produce and save an INO as a .bin. This option is in the "Sketch" drop down menu of the toolbar as "Export to binary" or similar. Did the motions and it loaded and displayed ready to send to an ST-Link. So to have at least two methods to load the code is great. Sorry to ramble on if you are already aware of this. I will check out the link you supplied.
Bob

**Comment by Bobbrockhouse** [comment]
Can report INO loaded, display and keypad all functioning.
Next phase will be a suitable case for the finished project.
Many thanks for your assistance, just great to see it running.
Cheers, Bob

**Comment by n1ksn** [comment]
Thank you for the update, Bob!  I never got around to putting a case on 
my throttle.  I attached it to a plastic base along with the DCC-EX 
command station and still use jumper wires for the connections.  :-)  
The only unexpected problem I ran into was quirky behavior due to 
inadequate 3.3V power after I added a wifi card to the CS.  I had to go 
back and retrofit a 5 to 3.3 volt converter chip to the throttle.  No 
problems since.  It's very satisfying for me to know someone actually 
built the throttle and I thank you again for you updates.  Cheers, Andy.

**Comment by Bobbrockhouse** [comment]
Thanks Andrew. Just did a full dress rehearsal , hooked up to a track with a
sound equipped loco. All good apart from my own errors in pushing the
right buttons. Did observe a faulty keypad key so a replacement pad is
on it's way. All in all the project is a great success.

If you ever plan on a version 8 , I would be first to try it out. At the same
time would love to see the display upsized to 1.3 inch SH1106 driver,
the current 0.96 inch is bare minimum. No offence intended, just wishful
thinking.

Cheers,Bob

**Comment by n1ksn** [comment]
Bob, thanks for the update.  I'm very glad it's working.  I'd recommend 
ordering a couple of those keypads, with one as a backup, as it's 
probably the weak link in the design.  And yes, that display is small.  
There are no plans for a version 8, but I'll keep your suggestion for a 
larger display in mind.  The small display fits my own setup well, but 
I'm in my late 70's and my vision isn't getting any better!

Cheers, Andy

**Comment by Bobbrockhouse** [comment]
Indeed I am in mid 70's also.  Had a try at making code changes to use
a 1.3 inch display. Total disaster needing to load a fresh copy of your
INO. No harm done to the working unit as I was trying the code changes
via the IDE verify first. I shall leave well enough alone. Coding is not my
forte.

Moving on, need to make choices for a case, that will keep me busy.

Cheers
